apiVersion: v1
kind: ServiceAccount
metadata:
  name: bank-dr-secret-reader
  namespace: bank-dr
  annotations:
    iam.gke.io/gcp-service-account: bank-dr-secrets@kdt4-1-506106.iam.gserviceaccount.com
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: bank-dr
spec:
  provider:
    gcpsm:
      projectID: kdt4-1-506106
      auth:
        workloadIdentity:
          clusterProjectID: kdt4-1-506106
          clusterLocation: asia-northeast3
          clusterName: phase1-bank-gke
          serviceAccountRef:
            name: bank-dr-secret-reader
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bank-app-runtime
  namespace: bank-dr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gcp-secret-manager
  target:
    name: bank-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: ACCOUNTS_DB_URI
      remoteRef:
        key: phase1-bank-app-runtime
        property: ACCOUNTS_DB_URI
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: phase1-bank-app-runtime
        property: SPRING_DATASOURCE_URL
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: phase1-bank-app-runtime
        property: SPRING_DATASOURCE_USERNAME
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: phase1-bank-app-runtime
        property: SPRING_DATASOURCE_PASSWORD
    - secretKey: REDIS_URL
      remoteRef:
        key: phase1-bank-app-runtime
        property: REDIS_URL
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bank-app-jwt
  namespace: bank-dr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gcp-secret-manager
  target:
    name: jwt-key
    creationPolicy: Owner
  data:
    - secretKey: jwtRS256.key
      remoteRef:
        key: phase1-bank-app-jwt
        property: jwtRS256.key
    - secretKey: jwtRS256.key.pub
      remoteRef:
        key: phase1-bank-app-jwt
        property: jwtRS256.key.pub
