\set ON_ERROR_STOP on

GRANT USAGE ON SCHEMA public TO :"dms_user";
GRANT USAGE ON SCHEMA pglogical TO PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO :"dms_user";
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO :"dms_user";
GRANT SELECT ON ALL TABLES IN SCHEMA pglogical TO :"dms_user";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON TABLES TO :"dms_user";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON SEQUENCES TO :"dms_user";
