/*
 * Bank of Anthos append-only ledger schema.
 * Source: googlecloudplatform/bank-of-anthos
 * src/ledger/ledger-db/initdb/0_init_tables.sql
 */

CREATE TABLE IF NOT EXISTS transactions (
  transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_acct CHAR(10) NOT NULL,
  to_acct CHAR(10) NOT NULL,
  from_route CHAR(9) NOT NULL,
  to_route CHAR(9) NOT NULL,
  amount INT NOT NULL,
  timestamp TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_transactions_from
  ON transactions (from_acct, from_route, timestamp);
CREATE INDEX IF NOT EXISTS idx_transactions_to
  ON transactions (to_acct, to_route, timestamp);

CREATE OR REPLACE RULE prevent_update AS
  ON UPDATE TO transactions
  DO INSTEAD NOTHING;

CREATE OR REPLACE RULE prevent_delete AS
  ON DELETE TO transactions
  DO INSTEAD NOTHING;
